"""Main table: zero-shot runs plus k-shot runs aggregated over seeds (mean ± std).

Writes results/main_table.json and results/RESULTS.md. Temperatures for "ECE after
temperature" are fit on each run's calib split (metrics.summary), never on test.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import numpy as np

from s1x import cache, metrics
from s1x.tasks import TASKS

RESULTS = Path(__file__).resolve().parents[2] / "results"
ZERO_SHOT = ("majority", "laya", "laya-ml", "nli")
FEW_SHOT = ("embed-lr", "setfit", "ft-ce")
PARITY_METHODS = ("setfit", "embed-lr")
METRICS = ("accuracy", "macro_f1", "ece", "ece_ts", "brier", "sel_acc@50", "sel_acc@80", "sel_acc@95",
           "p50_ms", "p95_ms", "mae", "qwk", "temperature")
SHOT_RE = re.compile(r"^(?P<method>.+)__k=(?P<k>\d+),seed=(?P<seed>\d+)\.jsonl$")


def _one(task: str, method: str, shot: str | None) -> dict:
    d = cache.read(task, method, shot)
    p, y, ms = d["test"]
    pc, yc, _ = d.get("calib", (None, None, None))
    s = metrics.summary(p, y, p_calib=pc, y_calib=yc, ordinal_task=TASKS[task].kind == "score")
    ok = ms[~np.isnan(ms)]
    s |= {"p50_ms": float(np.median(ok)) if len(ok) else None, "p95_ms": float(np.percentile(ok, 95)) if len(ok) else None}
    return s


def _few_shot_runs(task: str) -> dict[tuple[str, int], dict[int, str]]:
    runs: dict[tuple[str, int], dict[int, str]] = {}
    folder = cache.PREDS / task
    if not folder.exists():
        return runs
    for f in sorted(folder.iterdir()):
        m = SHOT_RE.match(f.name)
        if m and m["method"] in FEW_SHOT:
            runs.setdefault((m["method"], int(m["k"])), {})[int(m["seed"])] = f"k={m['k']},seed={m['seed']}"
    return runs


def build(task_names: list[str]) -> list[dict]:
    rows = []
    for task in task_names:
        for method in ZERO_SHOT:
            if cache.exists(task, method):
                s = _one(task, method, None)
                rows.append({"task": task, "method": method, "k": 0, "seeds": 1, "n": s["n"],
                             **{m: {"mean": s[m], "std": 0.0} for m in METRICS if s.get(m) is not None}})
        runs = _few_shot_runs(task)
        for (method, k), shots in sorted(runs.items(), key=lambda kv: (FEW_SHOT.index(kv[0][0]), kv[0][1])):
            per_seed = {seed: _one(task, method, shot) for seed, shot in sorted(shots.items())}
            row = {"task": task, "method": method, "k": k, "seeds": len(per_seed), "seed_ids": sorted(per_seed),
                   "n": next(iter(per_seed.values()))["n"]}
            for m in METRICS:
                vals = [s[m] for s in per_seed.values() if s.get(m) is not None]
                if vals:
                    row[m] = {"mean": float(np.mean(vals)), "std": float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0}
            rows.append(row)
    return rows


def parity(rows: list[dict], task: str) -> dict:
    laya = next((r for r in rows if r["task"] == task and r["method"] == "laya"), None)
    if laya is None:
        return {"laya_accuracy": None}
    target = laya["accuracy"]["mean"]
    out = {"laya_accuracy": target}
    for method in PARITY_METHODS:
        cand = sorted((r for r in rows if r["task"] == task and r["method"] == method), key=lambda r: r["k"])
        hit = next((r["k"] for r in cand if r["accuracy"]["mean"] >= target), None)
        out[method] = {"k": hit, "tried": [r["k"] for r in cand]}
    return out


def _fmt(cell: dict | None, digits: int = 3) -> str:
    if cell is None:
        return "–"
    if cell.get("std"):
        return f"{cell['mean']:.{digits}f} ± {cell['std']:.{digits}f}"
    return f"{cell['mean']:.{digits}f}"


def _ms(cell: dict | None) -> str:
    return "–" if cell is None else f"{cell['mean']:.1f}"


def markdown(rows: list[dict], task_names: list[str]) -> str:
    out = ["# Results", "",
           "Generated by `s1x report` from the cached predictions in `results/preds/`. Test = 1,000 fixed "
           "examples per task. k-shot rows are mean ± sample std over the seeds listed (k examples per class, "
           "draws committed in `data/splits/`). ECE uses 15 equal-width bins; \"ECE (TS)\" is after one "
           "temperature fit on the 500-example calib split. Sel@80 = accuracy on the 80% most-confident "
           "test examples. p50 latency is per example in single-example mode on an M1 (16 GB), model load "
           "excluded (few-shot: encode + head).", ""]
    for task in task_names:
        trs = [r for r in rows if r["task"] == task]
        if not trs:
            continue
        ordinal = TASKS[task].kind == "score"
        head = ["Method", "k", "seeds", "Accuracy", "Macro-F1", "ECE", "ECE (TS)", "Sel@80", "p50 ms"]
        if ordinal:
            head += ["MAE", "QWK"]
        out += [f"## {task}", "", "| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
        for r in trs:
            cells = [r["method"], str(r["k"]), str(r["seeds"]), _fmt(r.get("accuracy")), _fmt(r.get("macro_f1")),
                     _fmt(r.get("ece")), _fmt(r.get("ece_ts")), _fmt(r.get("sel_acc@80")), _ms(r.get("p50_ms"))]
            if ordinal:
                cells += [_fmt(r.get("mae")), _fmt(r.get("qwk"))]
            out.append("| " + " | ".join(cells) + " |")
        par = parity(rows, task)
        if par["laya_accuracy"] is not None:
            bits = []
            for method in PARITY_METHODS:
                info = par[method]
                if not info["tried"]:
                    bits.append(f"{method}: not run")
                elif info["k"] is not None:
                    bits.append(f"{method}: k={info['k']}")
                else:
                    bits.append(f"{method}: not reached by {max(info['tried'])}")
            hits = [par[m]["k"] for m in PARITY_METHODS if par[m]["tried"] and par[m]["k"] is not None]
            best = f"k={min(hits)} per class" if hits else (
                "not reached by 64" if any(par[m]["tried"] and max(par[m]["tried"]) >= 64 for m in PARITY_METHODS)
                else "not reached by the k values run so far")
            out += ["", f"**Labels to parity** (mean accuracy ≥ Laya zero-shot {par['laya_accuracy']:.3f}): "
                        f"{best} ({'; '.join(bits)})."]
        out.append("")

    lat = RESULTS / "latency.json"
    if lat.exists():
        b = json.loads(lat.read_text()).get("benchmark")
        if b:
            out += ["## Latency (same 200 AG News test examples, after warm-up)", "",
                    "| Setup | p50 ms/example | p95 ms/example | examples/s |", "|---|---|---|---|"]
            names = {"laya_single": "Laya, one example per pass", "nli_single": "NLI, one example per pass (all 4 hypotheses batched)",
                     "nli_pipeline_per_pair": "NLI, HF pipeline (one pass per hypothesis)",
                     "laya_batched": f"Laya, {b.get('laya_batched', {}).get('batch_states')} examples per pass",
                     "nli_batched": f"NLI, {b.get('nli_batched', {}).get('batch_examples')} examples per pass"}
            for key, label in names.items():
                if key in b:
                    s = b[key]
                    out.append(f"| {label} | {s['p50_ms']:.1f} | {s['p95_ms']:.1f} | {s['examples_per_s']:.1f} |")
            out += ["", "In batched mode, per-example latency is the pass wall time divided by the batch size.", ""]

    ov = RESULTS / "laya_overflow.json"
    if ov.exists():
        o = json.loads(ov.read_text())
        out += ["## Laya context (512 tokens): test inputs that do not fit", "",
                "| Task | text > 512 tokens | text > room left after question+options | room (tokens) | longest text (tokens) |",
                "|---|---|---|---|---|"]
        for task in task_names:
            if task in o:
                s = o[task]
                out.append(f"| {task} | {s['over_512']} | {s['state_truncated']} | {s['state_room']} | {s['max_state_tokens']} |")
        out.append("")
    return "\n".join(out)


def write(task_names: list[str]) -> list[dict]:
    rows = build(task_names)
    pars = {t: parity(rows, t) for t in task_names}
    RESULTS.mkdir(exist_ok=True)
    (RESULTS / "main_table.json").write_text(json.dumps({"rows": rows, "labels_to_parity": pars}, indent=1))
    (RESULTS / "RESULTS.md").write_text(markdown(rows, task_names))
    return rows
